### PR TITLE
Correctly format `unsafe` when preceding a `for` loop pattern.

### LINKED ISSUE #1183: `unsafe` in `for` loop incorrectly drops trailing trivia
When formatting e.g:

```swift
for unsafe x in xs {}
```

swift-format outputs:

```swift
for unsafex in xs {}
```

### PR DESCRIPTION
**Pull request by allevato**
Fixes #1183.

### CODE REVIEW

File: Sources/SwiftFormat/PrettyPrint/TokenStreamCreator.swift [hunk 1]
```diff
@@ -646,18 +646,21 @@ private final class TokenStreamCreator: SyntaxVisitor {
...
-        before(tryKeyword, tokens: .open)
-        after(tryKeyword, tokens: .break)
-        after(awaitKeyword, tokens: .close, .break)
+      if modifiers.count == 1 {
+        after(first, tokens: .break)
       } else {
-        after(awaitKeyword, tokens: .break)
+        before(first, tokens: .open)
+        for i in 0..<(modifiers.count - 1) {
+          after(modifiers[i], tokens: .break)
```
Comment (hamishknight) [inline Sources/SwiftFormat/PrettyPrint/TokenStreamCreator.swift]: `for modifier in modifiers.dropLast()`?

**Review by hamishknight — APPROVED** [review]
Thank you!

File: Sources/SwiftFormat/PrettyPrint/TokenStreamCreator.swift (hunk 1 above)
Comment (allevato) [reply Sources/SwiftFormat/PrettyPrint/TokenStreamCreator.swift]: Done.
